apiVersion: v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: ndohjapan/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis-10318.c16.us-east-1-3.ec2.cloud.redislabs.com"
            - name: REDIS_PORT
              value: "10318"
            - name: PGUSER
              value: "postgres"
            - name: PGHOST
              value: "containers-us-west-96.railway.app"
            - name: PGDATABASE
              value: "railway"
            - name: PGPASSWORD
              value: "6mSsa0jqQeQBwBivx3sA"
            - name: PGPORT
              value: "7459"
            - name: REDIS_USERNAME
              value: "default"
            - name: REDIS_PASSWORD
              value: "Tu6Q1fNDJNumCRyBzoeGaTqcTEkGsCVj"
---
apiVersion: v1
kind: Service 
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000