apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert-tls
spec:
  secretName: api-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.lcufeeding.com
  dnsNames:
    - api.lcufeeding.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - api.lcufeeding.com
